### ISSUE TITLE
Binding to IndependentList<string> means that everytime the collection is modified, the whole collection is enumerated

### ISSUE THREAD

**Issue by ymassad** [michaellperry/UpdateControls#14]
Consider the following example model and view model:

```
    public class ViewModel
    {
        private readonly Model model;

        public ViewModel(Model model)
        {
            this.model = model;
        }

        public IEnumerable<string> Data => model.Data.Select(
            x =>
            {
                Thread.Sleep(500);
                return x;
            });
    }

    public class Model
    {
        private readonly IndependentList<string> data = new IndependentList<string>();

        public IEnumerable<string> Data => data;

        public void Add(string s) => data.Add(s);
    }
```

If you bind to the `Data` property of the view model, and then you call `model.Add`, this will cause `ViewModel.Data` enumerable to be enumerated again.

`INotifyCollectionChanged.CollectionChanged` is raised which is good. But I think that only this event should be raised and WPF shouldn't have to enumerate the collection again. If the list has a huge number of items this will be a performance issue.

In the example, I wait 0.5 second to simulate the cost of enumeration.

The expected behavior is that when you add a new item, you should wait 0.5 seconds. However, currently you wait 0.5 * the number of items in the list.

I suggest something like this in the ViewModel:

`public IEnumerable<string> Data {get;} = new SomeDependentList(model.Data, x => { Thread.Sleep(500); return x;});`

`SomeDependentList` in this case wraps the independent list. When it receives the notification that an item was added, it transforms it via the function passed to it and then it sends a transformed notification to WPF.

**Comment by ymassad** [comment]
I have made more tests. If you simply bind to a simple `IndependentList<T>` property and then add some 200000 items, further additions (even adding 1 more item) are very slow. I think this is because every time we add a new item, the whole list is enumerated.

**Comment by michaellperry** [comment]
DependentList<T> performs object recycling, which will reuse objects in a collection. This helps in two ways: visual elements are reused between changes, and dependencies that recycled objects hold are not recomputed. For these reasons, I recommend using a collection of objects rather than simple values if you need some computation per item.

I also generally recommend against using IndependentList<T> for large data sets. Just as you would with any other client library, keep your large data sets in persistent storage, and load only what a user would reasonably want to scroll through.

**Comment by ymassad** [comment]
@michaellperry,

The list of strings I gave in the post is just an example, the same problem happens if the list item type is an object, e.g. `IndependentList<Person>`.

My main point is that the `IndependentList` could use `INotifyCollectionChanged.CollectionChanged` only to inform the UI about the changes. Currently, the UI always goes to enumerate the list every time an item is added to the list. Is there a reason why the UI must enumerate the list on every change?

If I simply create an object that implements `INotifyCollectionChanged` and `IEnumerable<T>`, and I raise the `CollectionChanged` event, WPF will not try to enumerate the object again.

I was hoping the there is a way to do this with `IndependentList`.

**Comment by ymassad** [comment]
Actually, doing more debugging, its UpdateControls that is enumerating the list on every change. This seems to be related to object recycling that you mentioned. I don't understand exactly the purpose of this feature and how it is implemented.

I don't think that I know about this enough to discuss it with you. But I am going to try :)

Why do you need to reuse the objects? The UI already has the list of objects. It only needs updates (additions/removals) to update the list. It will still reuse the visual elements for the existing items, or not?

In any case, with large lists, the cost of enumeration seems to be much more than other costs whatever they may be.

**Comment by michaellperry** [comment]
You are correct. UpdateControls is enumerating the list, and it is specifically to do object recycling.

There are a couple of reasons for reuse. First, it is for persistence of the UI. By recycling objects, Update Controls can optimize inserts and removals from lists. If the user has scrolled down, then their scroll position will be preserved after a change. If the user has selected an item, then that selection will be preserved.

The second reason is optimization. If you have a DependentList of objects, which themselves have dependent properties, then those dependencies are not updated just because the list changed. This situation arises frequently when you have a view model with a property that returns a collection of child view models. This property is backed by a DependentList within the wrapper, which performs object recycling. Then, even though you are projecting a bunch of new child view models, the existing child view models are recycled in their place. You just have to implement Equals and GetHashCode appropriately.

But, yes, object recycling does require an enumeration of the list. As long as the list is small and the projection function (Select) is simple, the cost is not measurable.
